### PR TITLE
Improved README.md

### PR DESCRIPTION
**Pull request by RobertvBraam**
- Restructured the README.md to have better overview on how to setup integration test environment.
- Fixed Git script
- Added some to be done items for the integration test project
- Added instructions how to create a local Bitbucket instance with Docker

### CODE REVIEW

**Comment by RobertvBraam** [comment]
First of all, thanks for your project @jlouros. It has helped me a lot with implementing custom tooling that use Bitbucket API. 
Secondly, in this pull request I changed up the README.md file, because I had an improvement on how to make a local instance with Docker, found some bugs and had the feeling it needed some cleanup. 
Next to that, I'm planning to add some more pull requests regarding managing pull requests in Bitbucket, the edit, approve, decline functionality. 
And last but not least, do you know how I can resolve the problem in step: "jlouros.StashApiCSharp — Unable to find './.pipeline/azure-pipelines.yml'"?

**Comment by jlouros** [comment]
Hi @RobertvBraam thanks for your contribution.
I did some experiments with Azure pipelines, but I didn't manage to find the time to complete this work.
The related PR is https://github.com/jlouros/StashApiCSharp/pull/56 
Hopefully I can find some time to finish the setup.

**Comment by RobertvBraam** [comment]
Is it possible to disable the "jlouros.StashApiCSharp — Unable to find './.pipeline/azure-pipelines.yml' " check while you are trying to fix this PR? Because then my PR can be merged.

**Comment by RobertvBraam** [comment]
@jlouros thank you for fixing the checks and merging the PR!

**Pull request merged**
