### PR TITLE
get repos sizes

### PR DESCRIPTION
**Pull request by jmecosta**
add repo size endpoint

### CODE REVIEW

**Comment by jlouros** [comment]
thanks for your contribution @jmecosta 

At the moment, I am refactoring the CI pipeline. Once I'm done with it, I will review this PR.

**Comment by jmecosta** [comment]
While doing it would be ok to drop  older .net frameworks and support only
.net standard? Now the projects are a bit all over the place. Or do you
need to support that? And also please dont forget to strong name all target
frameworks

**Comment by jlouros** [comment]
that's a good point @jmecosta 
The pipeline refactoring is taking me a lot more time because I was trying to support .Net Framework 4.5.
I will consider moving everything to .Net Standard 2.2

**Comment by jmecosta** [comment]
@jlouros how is the refactoring going, wanted to create a few more improvements GetUsers and its permissions

**Comment by jlouros** [comment]
hi @jmecosta sorry for the delay,
in the last months of 2020 I was absolutely piled up in work, I really needs 2 weeks to completely get away from the PC.
I will make sure I get it done this week.

Apologies for the delay.

**Comment by jlouros** [comment]
@jmecosta CI process still needs some work, but what is currently there should unblock you, can you try it out?

thanks

**Comment by jmecosta** [comment]
Yeah, I'm not blocked. Just want to create clean pull requests rebased
against the new CI

**Comment by jmecosta** [comment]
@jlouros please approve a merge!

**Pull request merged**
